version: "3.7"
services:

  interface:
    build: ./cmsinterface
    volumes:
      - static:/cmsinterface/interfaceapp/static

  api:
    build: ./cmsapi

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "81:81"
    restart: always
    depends_on:
      - interface
      - api
    volumes:
      - static:/gloudcmsd/cmsinterface/interfaceapp/static

volumes:
  static:
  