version: "3.7"
services:

  interface:
    build: ./cmsinterface
    environment:
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongopw
      MONGODB_HOSTNAME: mongodb
    volumes:
      - static:/cmsinterface/interfaceapp/static

  api:
    build: ./cmsapi
    environment:
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongopw
      MONGODB_HOSTNAME: mongodb

  mongodb:
    image: mongo
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
      MONGO_INITDB_DATABASE: gloudcms
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - data:/data/db
    

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "81:81"
    restart: always
    depends_on:
      - interface
      - api
    volumes:
      - static:/gloudcmsd/cmsinterface/interfaceapp/static

volumes:
  static:
  data:
  