user_info = {
    'id': '1234',
    'email': 'email@gmail.com',
    'verified_email': True,
    'name': 'name',
    'given_name': 'givenName',
    'family_name': 'familyName',
    'picture': 'pic',
    'locale': 'de'}

user_info_google_right = {'id': '117248067145484343890', 'email': 'dasmlgschaf@gmail.com', 'verified_email': True, 'name': 'Dasmlg Schaf', 'given_name': 'Dasmlg', 'family_name': 'Schaf', 'picture': 'https://lh6.googleusercontent.com/-GclbpHqiZKY/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rd9pF5rs6EOFe0GMmX_w6mmaxeW0g/photo.jpg', 'locale': 'de'}


class credentials():
    token = 4321
    refresh_token = 54321


raw_article = {
    "author": "Test",
    "title": "test",
    "url": "url",
    "tags": [
        "tag1",
        "tag2"],
    "content": "CONTENT"}

document_right = {
    'title': 'Test Document One', 'body': {
        'content': [
            {
                'endIndex': 1, 'sectionBreak': {
                    'sectionStyle': {
                        'columnSeparatorStyle': 'NONE', 'contentDirection': 'LEFT_TO_RIGHT'}}}, {
                            'startIndex': 1, 'endIndex': 8, 'paragraph': {
                                'elements': [
                                    {
                                        'startIndex': 1, 'endIndex': 8, 'textRun': {
                                            'content': 'Author\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}, {
                                                    'startIndex': 8, 'endIndex': 23, 'paragraph': {
                                                        'elements': [
                                                            {
                                                                'startIndex': 8, 'endIndex': 23, 'textRun': {
                                                                    'content': 'Philip Bizimis\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                                        'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}, {
                                                                            'startIndex': 23, 'endIndex': 24, 'paragraph': {
                                                                                'elements': [
                                                                                    {
                                                                                        'startIndex': 23, 'endIndex': 24, 'textRun': {
                                                                                            'content': '\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                                                                'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}, {
                                                                                                    'startIndex': 24, 'endIndex': 29, 'paragraph': {
                                                                                                        'elements': [
                                                                                                            {
                                                                                                                'startIndex': 24, 'endIndex': 29, 'textRun': {
                                                                                                                    'content': 'Tags\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                                                                                        'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}, {
                                                                                                                            'startIndex': 29, 'endIndex': 55, 'paragraph': {
                                                                                                                                'elements': [
                                                                                                                                    {
                                                                                                                                        'startIndex': 29, 'endIndex': 55, 'textRun': {
                                                                                                                                            'content': 'first,post,article,sports\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                                                                                                                'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}, {
                                                                                                                                                    'startIndex': 55, 'endIndex': 56, 'paragraph': {
                                                                                                                                                        'elements': [
                                                                                                                                                            {
                                                                                                                                                                'startIndex': 55, 'endIndex': 56, 'textRun': {
                                                                                                                                                                    'content': '\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                                                                                                                                        'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}, {
                                                                                                                                                                            'startIndex': 56, 'endIndex': 64, 'paragraph': {
                                                                                                                                                                                'elements': [
                                                                                                                                                                                    {
                                                                                                                                                                                        'startIndex': 56, 'endIndex': 64, 'textRun': {
                                                                                                                                                                                            'content': 'Content\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                                                                                                                                                                'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}, {
                                                                                                                                                                                                    'startIndex': 64, 'endIndex': 422, 'paragraph': {
                                                                                                                                                                                                        'elements': [
                                                                                                                                                                                                            {
                                                                                                                                                                                                                'startIndex': 64, 'endIndex': 422, 'textRun': {
                                                                                                                                                                                                                    'content': 'This is the first paragraph of this article but I changed it. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                                                                                                                                                                                        'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}, {
                                                                                                                                                                                                                            'startIndex': 422, 'endIndex': 423, 'paragraph': {
                                                                                                                                                                                                                                'elements': [
                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                        'startIndex': 422, 'endIndex': 423, 'textRun': {
                                                                                                                                                                                                                                            'content': '\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                                                                                                                                                                                                                'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}, {
                                                                                                                                                                                                                                                    'startIndex': 423, 'endIndex': 431, 'paragraph': {
                                                                                                                                                                                                                                                        'elements': [
                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                'startIndex': 423, 'endIndex': 431, 'textRun': {
                                                                                                                                                                                                                                                                    'content': 'Picture\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                                                                                                                                                                                                                                        'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}, {
                                                                                                                                                                                                                                                                            'startIndex': 431, 'endIndex': 610, 'paragraph': {
                                                                                                                                                                                                                                                                                'elements': [
                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                        'startIndex': 431, 'endIndex': 609, 'textRun': {
                                                                                                                                                                                                                                                                                            'content': 'https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/Brown_County_Hills_Leonetti.jpg?crop=33,0,1192,656&wid=4000&hei=2200&scl=0.29818181818181816', 'textStyle': {
                                                                                                                                                                                                                                                                                                'underline': True, 'foregroundColor': {
                                                                                                                                                                                                                                                                                                    'color': {
                                                                                                                                                                                                                                                                                                        'rgbColor': {
                                                                                                                                                                                                                                                                                                            'red': 0.06666667, 'green': 0.33333334, 'blue': 0.8}}}, 'link': {
                                                                                                                                                                                                                                                                                                                'url': 'https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/Brown_County_Hills_Leonetti.jpg?crop=33,0,1192,656&wid=4000&hei=2200&scl=0.29818181818181816'}}}}, {
                                                                                                                                                                                                                                                                                                                    'startIndex': 609, 'endIndex': 610, 'textRun': {
                                                                                                                                                                                                                                                                                                                        'content': '\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                                                                                                                                                                                                                                                                                            'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}, {
                                                                                                                                                                                                                                                                                                                                'startIndex': 610, 'endIndex': 611, 'paragraph': {
                                                                                                                                                                                                                                                                                                                                    'elements': [
                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                            'startIndex': 610, 'endIndex': 611, 'textRun': {
                                                                                                                                                                                                                                                                                                                                                'content': '\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                                                                                                                                                                                                                                                                                                                    'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}, {
                                                                                                                                                                                                                                                                                                                                                        'startIndex': 611, 'endIndex': 953, 'paragraph': {
                                                                                                                                                                                                                                                                                                                                                            'elements': [
                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                    'startIndex': 611, 'endIndex': 952, 'textRun': {
                                                                                                                                                                                                                                                                                                                                                                        'content': 'This is the second paragraph of this article. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'textStyle': {}}}, {
                                                                                                                                                                                                                                                                                                                                                                            'startIndex': 952, 'endIndex': 953, 'textRun': {
                                                                                                                                                                                                                                                                                                                                                                                'content': '\n', 'textStyle': {}}}], 'paragraphStyle': {
                                                                                                                                                                                                                                                                                                                                                                                    'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT'}}}]}, 'documentStyle': {
                                                                                                                                                                                                                                                                                                                                                                                        'background': {
                                                                                                                                                                                                                                                                                                                                                                                            'color': {}}, 'pageNumberStart': 1, 'marginTop': {
                                                                                                                                                                                                                                                                                                                                                                                                'magnitude': 72, 'unit': 'PT'}, 'marginBottom': {
                                                                                                                                                                                                                                                                                                                                                                                                    'magnitude': 72, 'unit': 'PT'}, 'marginRight': {
                                                                                                                                                                                                                                                                                                                                                                                                        'magnitude': 72, 'unit': 'PT'}, 'marginLeft': {
                                                                                                                                                                                                                                                                                                                                                                                                            'magnitude': 72, 'unit': 'PT'}, 'pageSize': {
                                                                                                                                                                                                                                                                                                                                                                                                                'height': {
                                                                                                                                                                                                                                                                                                                                                                                                                    'magnitude': 841.8897637795277, 'unit': 'PT'}, 'width': {
                                                                                                                                                                                                                                                                                                                                                                                                                        'magnitude': 595.2755905511812, 'unit': 'PT'}}}, 'namedStyles': {
                                                                                                                                                                                                                                                                                                                                                                                                                            'styles': [
                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                    'namedStyleType': 'NORMAL_TEXT', 'textStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                        'bold': False, 'italic': False, 'underline': False, 'strikethrough': False, 'smallCaps': False, 'backgroundColor': {}, 'foregroundColor': {
                                                                                                                                                                                                                                                                                                                                                                                                                                            'color': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                'rgbColor': {}}}, 'fontSize': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    'magnitude': 11, 'unit': 'PT'}, 'weightedFontFamily': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        'fontFamily': 'Arial', 'weight': 400}, 'baselineOffset': 'NONE'}, 'paragraphStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            'namedStyleType': 'NORMAL_TEXT', 'alignment': 'START', 'lineSpacing': 115, 'direction': 'LEFT_TO_RIGHT', 'spacingMode': 'COLLAPSE_LISTS', 'spaceAbove': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                'unit': 'PT'}, 'spaceBelow': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'unit': 'PT'}, 'borderBetween': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'color': {}, 'width': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'unit': 'PT'}, 'padding': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'unit': 'PT'}, 'dashStyle': 'SOLID'}, 'borderTop': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'color': {}, 'width': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'unit': 'PT'}, 'padding': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'unit': 'PT'}, 'dashStyle': 'SOLID'}, 'borderBottom': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'color': {}, 'width': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'unit': 'PT'}, 'padding': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'unit': 'PT'}, 'dashStyle': 'SOLID'}, 'borderLeft': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'color': {}, 'width': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'unit': 'PT'}, 'padding': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'unit': 'PT'}, 'dashStyle': 'SOLID'}, 'borderRight': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'color': {}, 'width': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'unit': 'PT'}, 'padding': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'unit': 'PT'}, 'dashStyle': 'SOLID'}, 'indentFirstLine': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'unit': 'PT'}, 'indentStart': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'unit': 'PT'}, 'indentEnd': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'unit': 'PT'}, 'keepLinesTogether': False, 'keepWithNext': False, 'avoidWidowAndOrphan': True, 'shading': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'backgroundColor': {}}}}, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'namedStyleType': 'HEADING_1', 'textStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'fontSize': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'magnitude': 20, 'unit': 'PT'}}, 'paragraphStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT', 'spaceAbove': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'magnitude': 20, 'unit': 'PT'}, 'spaceBelow': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'magnitude': 6, 'unit': 'PT'}, 'keepLinesTogether': True, 'keepWithNext': True}}, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'namedStyleType': 'HEADING_2', 'textStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'bold': False, 'fontSize': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'magnitude': 16, 'unit': 'PT'}}, 'paragraphStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT', 'spaceAbove': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'magnitude': 18, 'unit': 'PT'}, 'spaceBelow': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'magnitude': 6, 'unit': 'PT'}, 'keepLinesTogether': True, 'keepWithNext': True}}, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'namedStyleType': 'HEADING_3', 'textStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'bold': False, 'foregroundColor': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'color': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'rgbColor': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'red': 0.2627451, 'green': 0.2627451, 'blue': 0.2627451}}}, 'fontSize': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'magnitude': 14, 'unit': 'PT'}}, 'paragraphStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT', 'spaceAbove': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'magnitude': 16, 'unit': 'PT'}, 'spaceBelow': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'magnitude': 4, 'unit': 'PT'}, 'keepLinesTogether': True, 'keepWithNext': True}}, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'namedStyleType': 'HEADING_4', 'textStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'foregroundColor': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'color': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'rgbColor': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'red': 0.4, 'green': 0.4, 'blue': 0.4}}}, 'fontSize': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'magnitude': 12, 'unit': 'PT'}}, 'paragraphStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT', 'spaceAbove': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'magnitude': 14, 'unit': 'PT'}, 'spaceBelow': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'magnitude': 4, 'unit': 'PT'}, 'keepLinesTogether': True, 'keepWithNext': True}}, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'namedStyleType': 'HEADING_5', 'textStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'foregroundColor': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'color': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'rgbColor': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'red': 0.4, 'green': 0.4, 'blue': 0.4}}}, 'fontSize': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'magnitude': 11, 'unit': 'PT'}}, 'paragraphStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT', 'spaceAbove': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'magnitude': 12, 'unit': 'PT'}, 'spaceBelow': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'magnitude': 4, 'unit': 'PT'}, 'keepLinesTogether': True, 'keepWithNext': True}}, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'namedStyleType': 'HEADING_6', 'textStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'italic': True, 'foregroundColor': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'color': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'rgbColor': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'red': 0.4, 'green': 0.4, 'blue': 0.4}}}, 'fontSize': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'magnitude': 11, 'unit': 'PT'}}, 'paragraphStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT', 'spaceAbove': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'magnitude': 12, 'unit': 'PT'}, 'spaceBelow': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'magnitude': 4, 'unit': 'PT'}, 'keepLinesTogether': True, 'keepWithNext': True}}, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'namedStyleType': 'TITLE', 'textStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'fontSize': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'magnitude': 26, 'unit': 'PT'}}, 'paragraphStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT', 'spaceAbove': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'unit': 'PT'}, 'spaceBelow': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'magnitude': 3, 'unit': 'PT'}, 'keepLinesTogether': True, 'keepWithNext': True}}, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'namedStyleType': 'SUBTITLE', 'textStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'italic': False, 'foregroundColor': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'color': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'rgbColor': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'red': 0.4, 'green': 0.4, 'blue': 0.4}}}, 'fontSize': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'magnitude': 15, 'unit': 'PT'}, 'weightedFontFamily': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'fontFamily': 'Arial', 'weight': 400}}, 'paragraphStyle': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'namedStyleType': 'NORMAL_TEXT', 'direction': 'LEFT_TO_RIGHT', 'spaceAbove': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'unit': 'PT'}, 'spaceBelow': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'magnitude': 16, 'unit': 'PT'}, 'keepLinesTogether': True, 'keepWithNext': True}}]}, 'revisionId': 'AOV_f4_jvAqFWVzCeKB5kRVv4ly-uyqXdDRlAKovAJ3gd7wpve80NF3ldf5JRCFbuP6eI69FB6J7XhrOKbrygA', 'suggestionsViewMode': 'SUGGESTIONS_INLINE', 'documentId': '1iwr0svUf4eFpBDwI-ZslJrMYz3u0290PZHbN-GxZtsg'}

content_right = [{'pics': [],
                  'para': 'This is the first paragraph of this article but I changed it. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.'},
                 {'pics': [],
                  'para': 'Picture'},
                 {'pics': [],
                  'para': 'https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/Brown_County_Hills_Leonetti.jpg?crop=33,0,1192,656&wid=4000&hei=2200&scl=0.29818181818181816'},
                 {'pics': [],
                  'para': 'This is the second paragraph of this article. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.'}]

raw_article_right = {
    "author": "Philip Bizimis",
    "title": "Test Document One",
    "url": "test_document_one",
    "tags": [
        "first",
        "post",
        "article",
        "sports"],
    "content": content_right}

content_string_right = """Author
Philip Bizimis

Tags
first,post,article,sports

Content
This is the first paragraph of this article but I changed it. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

Picture
https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/Brown_County_Hills_Leonetti.jpg?crop=33,0,1192,656&wid=4000&hei=2200&scl=0.29818181818181816

This is the second paragraph of this article. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.\n"""

content_array_raw_right = [
    'Author',
    'Philip Bizimis',
    '',
    'Tags',
    'first,post,article,sports',
    '',
    'Content',
    'This is the first paragraph of this article but I changed it. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
    '',
    'Picture',
    'https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/Brown_County_Hills_Leonetti.jpg?crop=33,0,1192,656&wid=4000&hei=2200&scl=0.29818181818181816',
    '',
    'This is the second paragraph of this article. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
    ""]

content_array_right = list(filter(None, content_array_raw_right))

content_array_wrong = content_array_right.copy().pop(0)

content_right = [{'pics': [],
                  'para': 'This is the first paragraph of this article but I changed it. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.'},
                 {'pics': [],
                  'para': 'Picture'},
                 {'pics': [],
                  'para': 'https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/Brown_County_Hills_Leonetti.jpg?crop=33,0,1192,656&wid=4000&hei=2200&scl=0.29818181818181816'},
                 {'pics': [],
                  'para': 'This is the second paragraph of this article. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.'}]
