apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"443":"cdn-backendconfig"}}'
  name: gloudcms-interface
  labels:
    app: gloudcms
spec:
  type: NodePort
  selector:
    app: gloudcms
    tier: frontend
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP